### ISSUE TITLE
including extracts from an old contrib

### ISSUE THREAD

**Issue by Casteran** [coq-community/hydra-battles#15]
I would like to use a small part of a contrib by Russel Oconnor (Goedel). I'm interested in the formalisation of primitive recursive functions, not in the proof of Gödel's theorem. The full contrib seems to be unmaintained after Coq 8.10, together with the pocklington contrib, which it requires (but not in the part I'm interested in)

The simplest solution would be to include just three. .v files in theories/ordinals/   and add credits to Russel.

What do you think ?

**Comment by Zimmi48** [comment]
Yes, I agree that it would make sense to copy just these three files as it would cut the dependency on pocklington.

**Comment by Casteran** [comment]
Ok.
 I copy the files on primitive recursive functions into hydra-battles, and  maintain independently goedel and pollington for their scientific and pedagogical interest.

Envoyé de mon iPad

**Comment by Casteran** [comment]
@Zimmi48 @palmskog 
Te branch with-ackermann has been made quickly (by naively copying files). It iits structure is OK, there should  exist
a way to move these files from a project to another ?

**Comment by Zimmi48** [comment]
Yes, there are tricks to move files while keeping the git history thanks to `git subtree`.

**Comment by palmskog** [comment]
It's fine by me to move the Ackermann library to hydra-battles for easier development, but at the same time I believe:
- we should leave the rest of Gödel's incompleteness theorem in the `goedel` repo, not least for visibility reasons - this is basically an important Coq formalization milestone that should be easy to locate
- we should make sure the `goedel` repo and package can build properly with hydra-battles as a dependency
- we should preserve the history of the Ackermann library via `git subtree`

How does that sound to you @Zimmi48?

**Comment by Zimmi48** [comment]
Sounds good to me.

**Comment by Casteran** [comment]
@palmskog @Zimmi48 

Perhaps the (present and future) maintainers of hydra-battles should  follow the following politics 
- add doc, bullets, etc, to the historical modules of Ackermann
- do not modify statements, implicit arguments, names of these modules,  
- useful changes may be done in new modules, not required by Goedel

We may write  such a warning in the README

**Comment by palmskog** [comment]
@Casteran I agree in general, but I think it's fine to change statements and module names conservatively as long as pull requests are submitted to the goedel repo in reasonable time (so that each Coq stable version has a working release of the incompleteness theorem).

**Comment by palmskog** [comment]
I think we can close this issue now, please reopen if it becomes relevant again.
