### ISSUE TITLE
Archiving the superceded coq-contribs

### ISSUE THREAD

**Issue by palmskog** [coq-community/hydra-battles#17]
How is the "addition chains" part of the repo related to the [additions contrib](https://github.com/coq-contribs/additions/)? If there is substantial overlap, then I think we should archive the contrib repo and link to here.

**Comment by Zimmi48** [comment]
Indeed, from my understanding the plan was to document `coq-addition-chains` as the successor of `coq-additions` (and same for `coq-hydra-battles` with respect to `coq-cantor`). But maybe only once it's released on opam?

**Comment by Casteran** [comment]
That’s right. The repos on coq-community are extended versions of the old contribs. I think that for versions of Coq >= 8.12, only the community stuff should be available 

Envoyé de mon iPhone

**Comment by palmskog** [comment]
OK, it sounds like a good plan to only archive `additions` and `cantor` once a release for Coq >= 8.12 is out on opam.
