### ISSUE TITLE
Generating coqdoc on merge to master

### ISSUE THREAD

**Issue by palmskog** [coq-community/hydra-battles#19]
@Zimmi48 could it be a good idea to generate coqdoc HTML on all merges to master in the same CI job as the LaTeX one? Maybe this approach to documentation could be used for additional projects until we have more automation for releases?

**Comment by palmskog** [comment]
coqdoc can work without having to compile the project, but it will then not have any cross-references between files/projects. For that, the `.glob` files are needed which can only be obtained after compilation. But maybe coqdoc without cross-references is good enough for now?

**Comment by Casteran** [comment]
Coqdoc uses the .glob files to generate links between different .v files. 
If the .glob are absent (or too old ?), it generates a warning.

**Comment by Zimmi48** [comment]
This was fixed by @start974 in #40.
