### ISSUE TITLE
Tagline for the project

### ISSUE THREAD

**Issue by palmskog** [coq-community/hydra-battles#23]
We discussed the current tagline for the project on Zulip, and there seems to be consensus that "funny maths" sounds a bit weird. I theorized that it may be a translation of *mathématiques amusantes*, whence a more reasonable translation to UK English might be "entertaining maths" or just plain "interesting maths". However, since we seem to lean towards US English in coq-community, maybe:
> Variations on Kirby & Paris' hydra battles and other entertaining math (collaborative, documented, includes exercises)

**Comment by Casteran** [comment]
Ok!

Envoyé de mon iPhone
