### ISSUE TITLE
Branch dev fails to compile with 8.11

### ISSUE THREAD

**Issue by Casteran** [coq-community/hydra-battles#27]
@palmskog @Zimmi48 

The branch dev seems to fail with 8.11, probably because of a lemma VectorSpec.Forall_forall (OK in 8.12 and 8.13).
Should we maintain 8.11 compatibility (with a proof of this lemma) ?

**Comment by Casteran** [comment]
@palmskog @Zimmi48 
Added a proof of Forall_forall in Prelude/MoreVectors;  works now from 8.11 to 8.13

**Comment by Zimmi48** [comment]
Great! But I think the solution of removing 8.11 compatibility would also have been reasonable.

**Comment by Casteran** [comment]
I agree! Anyway, we will have to remove 8.11 when the changes about Hint attributes are done.
The branch remove-8-11 still shows conflicts. May you have a look at it, and merge if possible ?

Meanwhile, I will document the examples about PR functions : They are nice examples to show some features of dependent types: vectors, eqdep, etc. In the litterature, the  usual proofs on PR functions heavily use dots "x1 ... xn" while, in Coq,
we have to use explicit induction on n.
