### ISSUE TITLE
Some use of Equations make 8.11 and 8.12 fail

### ISSUE THREAD

**Issue by Casteran** [coq-community/hydra-battles#30]
In the file theories/ordinals/MoreAck/Ack.v I added a small example of Equations (from a post by @anton-trunov).
If I remove the (noind) option, it fails on 8.11 and 8.12, and signals a warning on 8.13 and 8.13.dev (but  it compiles)
(Commit  11c4323)

Warning:
Solve Obligations tactic returned error: Proof is not complete.
This will become an error in the future [solve_obligation_error,tactics]
1 obligation remaining
Obligation 1 of Ack_graph_correct:
(forall p : nat * nat, Ack_graph p (Ack p)).
Warning:
Functional induction principle could not be proved automatically, it is left as an obligation.

the opam version of equations is 1.2.4+8.13 (installed yesterday)

@palmskog @Zimmi48 @anton-trunov 

Which is the best solution ?
-  Waiting for coq-equations to stabilize, add a (noind) to Ackermann's equations ? 
-  Removing 8.11 and 8.12 ?

**Comment by Zimmi48** [comment]
Unfortunately, I don't know enough about Equations to answer to this question. But it's likely that you would get one by asking on https://coq.zulipchat.com/#narrow/stream/237659-Equations-devs.20.26.20users. Matthieu and other people are pretty active there.

**Comment by Casteran** [comment]
In fact, it seems to be a bug.
My equations for a function Ack were defined inside a module called Alt, and there was another function with the same base name (outside any module).
If I rename my function, say, into Ack’, the functional induction principle is correctly built. 
Thus, I imagine there is some issue with qualified names ?

This afternoon, I will prepare a minimal file with the same issue, and send it to Matthieu at al.

**Comment by Casteran** [comment]
Sent an issue to the Equations project.
Meanwhile, I shamelessly renamed "Ack" into "ack" inside a module.
