### ISSUE TITLE
`make pdf` can succeed with failed snippets.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/hydra-battles#60]
I'm currently trying to build the PDF document with a Nix-installed Alectryon and SerAPI and I'm facing some issues which lead to external Coq modules not being found. This has led me to discover some issues when some snippet evaluation fails.

On page 194 of the PDF, I get the unexpected output:

```
The reference naryFunc was not found in the current environment.
```

But still the PDF was built successfully. This means that errors in PDF generation could go undetected.

In this case, the snippet is `movies/snippets/AckNotPR/majorizedDefs`. Running `make AckNotPR.tex` in `doc/movies` gives:

```
Convert '../../theories/ordinals/MoreAck/AckNotPR.v' to latex.
<string>:(11:4)-(11:68): (WARNING/2) Coq raised an exception:
     > Cannot load Equations.Init: no physical path bound to Equations
     >
   The offending chunk is delimited by >>>…<<< below:
     >
     >
     > >>>Require Import primRec Arith ArithRing List Ack MoreVectors Lia.<<<
     > Require Import Compare_dec Max.
     > Import extEqualNat  VectorNotations. 
   Results past this point may be unreliable.
```

and a lot more similar warnings but in the end the command exits with success.

This comes directly from the behavior of the underlying `python3 extract_snippets.py AckNotPR.tex -o ./snippets/ -d -R ../../theories/ordinals hydras` command.

And this probably comes in turn from Alectryon not raising an exception in such cases. I don't know if there is a way to make Alectryon raise an exception instead of printing a warning (cc @cpitclaudel).

To reproduce, I guess you just need to uninstall Equations before running `make pdf` (but after having built all the `vo` files with `make`).

**Comment by cpitclaudel** [comment]
Ah, yes, I think this will be fixed by this recent commit: https://github.com/cpitclaudel/alectryon/commit/dffde22c19b60af7ac9e16fcff6eab8851780d76 :

> The exit code produced by Alectryon indicates whether the conversion succeeded: 0 for success, 1 for a generic error, and 10 + the level of the most severe Docutils error if using a Docutils-based pipeline (hence 10 is debug, 11 is info, 12 is warning, 13 is error, and 14 is severe error). Docutils errors at levels below exit_status_level (default: 3) do not affect the exit code, so level 10, 11, and 12 are not used by default.

IOW, the latest Alectryon should exit with error code 13 in that case; can you check that it does?

**Comment by Zimmi48** [comment]
Thanks for your answer!

Maybe I did something wrong while applying the patch, but it seems that it doesn't change the exit status of Alectryon. Maybe this commit alone was not sufficient?

**Comment by cpitclaudel** [comment]
You need the one right before as well, `a310ec5c * core, docutils: Revamp error reporting in the SerAPI module`

**Comment by Zimmi48** [comment]
Thanks! I tested the latest version of `master` now (`d5c5229bbd30ece1b734071a6d9c26c3d9b1e9f2`). It does change the behavior when calling Alectryon directly. However, it doesn't change the behavior of our `extract_snippets.py` script :disappointed: . But that's on us to fix that.

in passing, I encountered an issue specific to `/tmp` that I hadn't encountered before:

```
Traceback (most recent call last):
  File "/nix/store/r9aa19mnzj45mfn08q6lfxcy70hjwfld-python3.9-alectryon-1.3.1/bin/.alectryon-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/r9aa19mnzj45mfn08q6lfxcy70hjwfld-python3.9-alectryon-1.3.1/lib/python3.9/site-packages/alectryon/cli.py", line 751, in main
    sys.exit(max(process_pipelines(args), default=0))
  File "/nix/store/r9aa19mnzj45mfn08q6lfxcy70hjwfld-python3.9-alectryon-1.3.1/lib/python3.9/site-packages/alectryon/cli.py", line 745, in process_pipelines
    state = call_pipeline_step(step, state, ctx)
  File "/nix/store/r9aa19mnzj45mfn08q6lfxcy70hjwfld-python3.9-alectryon-1.3.1/lib/python3.9/site-packages/alectryon/cli.py", line 698, in call_pipeline_step
    return step(state, **{p: ctx[p] for p in params})
  File "/nix/store/r9aa19mnzj45mfn08q6lfxcy70hjwfld-python3.9-alectryon-1.3.1/lib/python3.9/site-packages/alectryon/cli.py", line 258, in copy_assets
    copy_fn(src, dst)
  File "/nix/store/81lwy2hfqj4c1943b1x8a0qsivjhdhw9-python3-3.9.6/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/tmp/alectryon.js
```

**Comment by cpitclaudel** [comment]
> Any hint on how we can fix that?

Yes, of course.  Let me have a quick look.
